import { Sparkles } from "lucide-react";
import { useCallback, useEffect, useState } from "react";

import { api } from "../api/client";
import type { Insight } from "../api/types";
import { cn } from "../lib/utils";
import { Skeleton } from "./LoadingStates";

interface InsightCardProps {
  seriesId: number;
  episodeId?: number;
  compact?: boolean;
  autoLoad?: boolean;
}

type State =
  | { status: "idle" }
  | { status: "loading" }
  | { status: "error"; message: string }
  | { status: "ready"; insight: Insight };

export function InsightCard({
  seriesId,
  episodeId,
  compact = false,
  autoLoad = true,
}: InsightCardProps) {
  const [state, setState] = useState<State>({ status: "idle" });

  const load = useCallback(async () => {
    setState({ status: "loading" });
    try {
      const insight = episodeId
        ? await api.episodeInsight(seriesId, episodeId)
        : await api.seriesInsight(seriesId);
      setState({ status: "ready", insight });
    } catch (e) {
      const message = e instanceof Error ? e.message : "Insight unavailable";
      setState({ status: "error", message });
    }
  }, [seriesId, episodeId]);

  useEffect(() => {
    if (autoLoad) void load();
  }, [autoLoad, load]);

  const isFallback =
    state.status === "ready" && state.insight.source === "heuristic:fallback";

  return (
    <section
      aria-label="AI insight"
      className={cn(
        "card border-accent/50 bg-accent/5",
        compact ? "p-3" : "p-4 sm:p-5",
      )}
    >
      <header className="mb-2 flex items-center justify-between gap-2">
        <h3 className="inline-flex items-center gap-2 text-sm font-semibold text-accent">
          <Sparkles size={16} />
          {episodeId ? "Episode insight" : "Series insight"}
        </h3>
        {state.status === "ready" && (
          <span
            className={cn(
              "rounded-chip px-2 py-0.5 font-mono text-[11px]",
              isFallback
                ? "bg-elevated text-text-muted"
                : "bg-accent/15 text-accent",
            )}
            title={
              isFallback
                ? "Generated from genres and your progress; the AI model was unavailable."
                : "Generated by an LLM"
            }
          >
            {isFallback ? "smart summary" : "AI"}
          </span>
        )}
      </header>

      {state.status === "idle" && (
        <button
          type="button"
          onClick={() => void load()}
          className="focus-ring rounded-btn bg-accent px-3 py-1.5 text-sm font-semibold text-white hover:bg-accent/90 transition"
        >
          Generate insight
        </button>
      )}
      {state.status === "loading" && (
        <div className="space-y-2">
          <Skeleton className="h-3 w-full bg-accent/20" />
          <Skeleton className="h-3 w-11/12 bg-accent/20" />
          <Skeleton className="h-3 w-2/3 bg-accent/20" />
        </div>
      )}
      {state.status === "error" && (
        <div className="flex items-center justify-between gap-3">
          <p className="text-sm text-text-secondary">{state.message}</p>
          <button
            type="button"
            onClick={() => void load()}
            className="focus-ring text-sm text-accent underline-offset-2 hover:underline"
          >
            Retry
          </button>
        </div>
      )}
      {state.status === "ready" && (
        <>
          <p className="text-sm leading-relaxed text-text-primary">
            {state.insight.text}
          </p>
          {state.insight.highlights.length > 0 && (
            <div className="mt-3 flex flex-wrap gap-1.5">
              {state.insight.highlights.map((h) => (
                <span
                  key={h}
                  className="rounded-chip border border-accent/30 px-2 py-0.5 text-xs text-accent"
                >
                  {h}
                </span>
              ))}
            </div>
          )}
          {isFallback && (
            <p className="mt-3 text-xs text-text-muted">
              AI model unavailable right now; this summary is built from
              genres, ratings and your progress.
            </p>
          )}
        </>
      )}
    </section>
  );
}
